# Generated by Django 4.2 on 2026-02-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipanteRoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('premio', models.CharField(max_length=255)),
                ('canal_origem', models.CharField(default='Online', max_length=100)),
                ('status', models.CharField(choices=[('reservado', 'Reservado'), ('ganhou', 'Ganhou'), ('inviavel_tec', 'Inviável Tecnicamente'), ('inviavel_cani', 'Inviável Cani')], default='reservado', max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Participante da Roleta',
                'verbose_name_plural': 'Participantes da Roleta',
            },
        ),
        migrations.CreateModel(
            name='PremioRoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField(default=0)),
                ('localidade', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Prêmio da Roleta',
                'verbose_name_plural': 'Prêmios da Roleta',
            },
        ),
    ]
