# Generated by Django 4.2 on 2026-02-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanteroleta',
            name='perfil_cliente',
            field=models.CharField(default='nao', max_length=10),
        ),
    ]
