# Generated by Django 4.2 on 2026-02-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleta', '0003_alter_participanteroleta_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanteroleta',
            name='id_cliente_hubsoft',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
