# Generated by Django 4.2 on 2026-02-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleta', '0004_participanteroleta_id_cliente_hubsoft'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouletteAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('frame', 'Frame da Roleta'), ('background', 'Fundo da Página'), ('logo', 'Logo Central'), ('pointer', 'Ponteiro/Seta')], default='frame', max_length=20)),
                ('ordem', models.IntegerField(default=0, help_text='0-12 para frames')),
                ('imagem', models.ImageField(upload_to='roleta/assets/')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Asset da Roleta',
                'verbose_name_plural': 'Assets da Roleta',
                'ordering': ['tipo', 'ordem'],
            },
        ),
        migrations.AddField(
            model_name='premioroleta',
            name='posicoes',
            field=models.CharField(default='1', help_text='Posições na roleta (ex: 4,7)', max_length=50),
        ),
    ]
