# Generated by Django 4.2 on 2026-02-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleta', '0005_rouletteasset_premioroleta_posicoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoletaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo_giro', models.IntegerField(default=10, help_text='Pontos necessários para girar a roleta')),
                ('nome_clube', models.CharField(default='Clube MegaLink', max_length=100)),
            ],
            options={
                'verbose_name': 'Configuração da Roleta',
                'verbose_name_plural': 'Configurações da Roleta',
            },
        ),
        migrations.AddField(
            model_name='participanteroleta',
            name='saldo',
            field=models.IntegerField(default=0, help_text='Saldo de pontos do membro'),
        ),
    ]
