# Generated by Django 4.2 on 2026-02-24 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roleta', '0006_roletaconfig_participanteroleta_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembroClube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('saldo', models.IntegerField(default=0, help_text='Saldo acumulado de pontos')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('id_cliente_hubsoft', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Membro do Clube',
                'verbose_name_plural': 'Membros do Clube',
            },
        ),
        migrations.AddField(
            model_name='participanteroleta',
            name='membro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giros', to='roleta.membroclube'),
        ),
    ]
