# Generated by Django 4.2 on 2026-02-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleta', '0007_membroclube_participanteroleta_membro'),
    ]

    operations = [
        migrations.AddField(
            model_name='premioroleta',
            name='probabilidade',
            field=models.IntegerField(default=1, help_text='Peso da probabilidade (ex: 1 para raro, 10 para comum)'),
        ),
    ]
