# Generated by Django 4.2 on 2026-02-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleta', '0008_premioroleta_probabilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='membroclube',
            name='validado',
            field=models.BooleanField(default=False, help_text='Se o membro já validou o OTP'),
        ),
    ]
