# Generated by Django 4.2 on 2026-02-26 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roleta', '0009_membroclube_validado'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelClube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Bronze, Prata, Ouro', max_length=50)),
                ('xp_necessario', models.IntegerField(default=0, help_text='XP mínimo para alcançar este nível')),
                ('ordem', models.IntegerField(default=1, help_text='Ordem de exibição (1 é o mais baixo)')),
            ],
            options={
                'verbose_name': 'Nível do Clube',
                'verbose_name_plural': 'Níveis do Clube',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='RegraPontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatilho', models.CharField(help_text='Identificador único (ex: cadastro, indicacao)', max_length=50, unique=True)),
                ('nome_exibicao', models.CharField(help_text='Ex: Bônus de Boas Vindas', max_length=100)),
                ('pontos_saldo', models.IntegerField(default=0, help_text='Quantos Giros/Saldo a pessoa ganha')),
                ('pontos_xp', models.IntegerField(default=0, help_text='Quanto XP a pessoa ganha')),
                ('limite_por_membro', models.IntegerField(default=1, help_text='Quantas vezes um mesmo membro pode ganhar? (0 para iimitado)')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regra de Pontuação',
                'verbose_name_plural': 'Regras de Pontuação',
            },
        ),
        migrations.AddField(
            model_name='membroclube',
            name='xp_total',
            field=models.IntegerField(default=0, help_text='Experiência acumulada (Define o Nível)'),
        ),
        migrations.AlterField(
            model_name='membroclube',
            name='saldo',
            field=models.IntegerField(default=0, help_text='Saldo acumulado de pontos (Giros)'),
        ),
        migrations.CreateModel(
            name='ExtratoPontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_saldo_ganhos', models.IntegerField(default=0)),
                ('pontos_xp_ganhos', models.IntegerField(default=0)),
                ('descricao_extra', models.CharField(blank=True, help_text='Ex: Indicou CPF 123456789', max_length=255, null=True)),
                ('data_recebimento', models.DateTimeField(auto_now_add=True)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extratos', to='roleta.membroclube')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roleta.regrapontuacao')),
            ],
            options={
                'verbose_name': 'Extrato de Pontuação',
                'verbose_name_plural': 'Extratos de Pontuação',
            },
        ),
    ]
