# Generated by Django 4.2 on 2026-02-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleta', '0010_nivelclube_regrapontuacao_membroclube_xp_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletaconfig',
            name='xp_por_giro',
            field=models.IntegerField(default=5, help_text='Quantidade de XP ganha a cada giro da roleta'),
        ),
    ]
