# Generated by Django 4.2 on 2026-02-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleta', '0011_roletaconfig_xp_por_giro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='premioroleta',
            name='localidade',
        ),
        migrations.AddField(
            model_name='premioroleta',
            name='cidades_permitidas',
            field=models.ManyToManyField(blank=True, help_text='Selecione as cidades permitidas. Se deixar vazio, o prêmio valerá para QUALQUER cidade.', related_name='premios', to='roleta.cidade'),
        ),
    ]
