# Generated by Django 4.2 on 2026-01-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_configuracaosite_termos_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='codigo_especial',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Especial'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='modo_premium',
            field=models.BooleanField(default=False, verbose_name='Modo Premium'),
        ),
    ]
