# Generated by Django 4.2 on 2026-01-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_configuracao_codigo_especial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner'),
        ),
    ]
