# Generated by Django 4.2 on 2026-01-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_configuracaosite_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='titulo',
            field=models.CharField(default='Mega Sorteio', max_length=255, verbose_name='Título do Site'),
        ),
    ]
