# Generated by Django 4.2 on 2026-02-02 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_configuracaosite_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='codigo_especial',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='modo_premium',
        ),
    ]
